liip_imagine:
    filter_sets:
        cacher: ~

        profile:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }

        nav:
            quality: 75
            filters:
                thumbnail: { size: [75, 75], mode: outbound }

        questionnaire:
            quality: 75
            filters:
                relative_resize: 
                    widen: 700

        question:
            quality: 75
            filters:
                relative_resize: 
                    widen: 500
